import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output
import datetime
import prediction


app = dash.Dash()
app.layout = html.Div(children=[
    html.H1('Prediksi Harga Saham Menggunakan Machine Learning',
            className='title has-text-centered',),
    html.H2('Grafik Harga ini delayed'),
    html.P('*Disclaimer On'),
    html.P('Prediksi Menggunakan Supervised learning dari harga di masa lalu'),
    html.P('Prediksi Menggunakan Beberapa Metode Algoritma Machine Learning'),
    html.P('Data Diambil Menggunakan API dari situs Yahoo Finance dan Bursa Effek Indonesia'),
    dcc.Dropdown(
        id='input',
        options=[
            {'value': 'AALI.JK', 'label': 'Astra Agro Lestari Tbk.'},
            {'value': 'ABBA.JK', 'label': 'Mahaka Media Tbk.'},
            {'value': 'ABDA.JK', 'label': 'Asuransi Bina Dana Arta Tbk.'},
            {'value': 'ABMM.JK', 'label': 'ABM Investama Tbk.'},
            {'value': 'ACES.JK', 'label': 'Ace Hardware Indonesia Tbk.'},
            {'value': 'ACST.JK', 'label': 'Acset Indonusa Tbk.'},
            {'value': 'ADES.JK', 'label': 'Akasha Wira International Tbk.'},
            {'value': 'ADHI.JK', 'label': 'Adhi Karya (Persero) Tbk.'},
            {'value': 'ADMF.JK', 'label': 'Adira Dinamika Multi Finance Tbk.'},
            {'value': 'ADMG.JK', 'label': 'Polychem Indonesia Tbk.'},
            {'value': 'ADRO.JK', 'label': 'Adaro Energy Tbk.'},
            {'value': 'AGAR.JK', 'label': 'Asia Sejahtera Mina Tbk.'},
            {'value': 'AGII.JK', 'label': 'Aneka Gas Industri Tbk.'},
            {'value': 'AGRO.JK', 'label': 'Bank Rakyat Indonesia Agroniaga Tbk.'},
            {'value': 'AGRS.JK', 'label': 'Bank IBK Indonesia Tbk.'},
            {'value': 'AHAP.JK', 'label': 'Asuransi Harta Aman Pratama Tbk.'},
            {'value': 'AIMS.JK', 'label': 'Akbar Indo Makmur Stimec Tbk.'},
            {'value': 'AISA.JK', 'label': 'FKS Food Sejahtera Tbk.'},
            {'value': 'AKKU.JK', 'label': 'Anugerah Kagum Karya Utama Tbk.'},
            {'value': 'AKPI.JK', 'label': 'Argha Karya Prima Industry Tbk.'},
            {'value': 'AKRA.JK', 'label': 'AKR Corporindo Tbk.'},
            {'value': 'AKSI.JK', 'label': 'Maming Enam Sembilan Mineral Tbk.'},
            {'value': 'ALDO.JK', 'label': 'Alkindo Naratama Tbk.'},
            {'value': 'ALKA.JK', 'label': 'Alakasa Industrindo Tbk.'},
            {'value': 'ALMI.JK', 'label': 'Alumindo Light Metal Industry Tbk.'},
            {'value': 'ALTO.JK', 'label': 'Tri Banyan Tirta Tbk.'},
            {'value': 'AMAG.JK', 'label': 'Asuransi Multi Artha Guna Tbk.'},
            {'value': 'AMAN.JK', 'label': 'Makmur Berkah Amanda Tbk.'},
            {'value': 'AMAR.JK', 'label': 'Bank Amar Indonesia Tbk.'},
            {'value': 'AMFG.JK', 'label': 'Asahimas Flat Glass Tbk.'},
            {'value': 'AMIN.JK', 'label': 'Ateliers Mecaniques D Indonesia Tbk.'},
            {'value': 'AMOR.JK', 'label': 'Ashmore Asset Management Indonesia Tbk.'},
            {'value': 'AMRT.JK', 'label': 'Sumber Alfaria Trijaya Tbk.'},
            {'value': 'ANDI.JK', 'label': 'Andira Agro Tbk.'},
            {'value': 'ANJT.JK', 'label': 'Austindo Nusantara Jaya Tbk.'},
            {'value': 'ANTM.JK', 'label': 'Aneka Tambang Tbk.'},
            {'value': 'APEX.JK', 'label': 'Apexindo Pratama Duta Tbk.'},
            {'value': 'APIC.JK', 'label': 'Pacific Strategic Financial Tbk.'},
            {'value': 'APII.JK', 'label': 'Arita Prima Indonesia Tbk.'},
            {'value': 'APLI.JK', 'label': 'Asiaplast Industries Tbk.'},
            {'value': 'APLN.JK', 'label': 'Agung Podomoro Land Tbk.'},
            {'value': 'ARCI.JK', 'label': 'Archi Indonesia Tbk.'},
            {'value': 'ARGO.JK', 'label': 'Argo Pantes Tbk.'},
            {'value': 'ARII.JK', 'label': 'Atlas Resources Tbk.'},
            {'value': 'ARKA.JK', 'label': 'Arkha Jayanti Persada Tbk.'},
            {'value': 'ARMY.JK', 'label': 'Armidian Karyatama Tbk.'},
            {'value': 'ARNA.JK', 'label': 'Arwana Citramulia Tbk.'},
            {'value': 'ARTA.JK', 'label': 'Arthavest Tbk.'},
            {'value': 'ARTI.JK', 'label': 'Ratu Prabu Energi Tbk.'},
            {'value': 'ARTO.JK', 'label': 'Bank Jago Tbk.'},
            {'value': 'ASBI.JK', 'label': 'Asuransi Bintang Tbk.'},
            {'value': 'ASDM.JK', 'label': 'Asuransi Dayin Mitra Tbk.'},
            {'value': 'ASGR.JK', 'label': 'Astra Graphia Tbk.'},
            {'value': 'ASII.JK', 'label': 'Astra International Tbk.'},
            {'value': 'ASJT.JK', 'label': 'Asuransi Jasa Tania Tbk.'},
            {'value': 'ASMI.JK', 'label': 'Asuransi Maximus Graha Persada Tbk.'},
            {'value': 'ASPI.JK', 'label': 'Andalan Sakti Primaindo Tbk.'},
            {'value': 'ASRI.JK', 'label': 'Alam Sutera Realty Tbk.'},
            {'value': 'ASRM.JK', 'label': 'Asuransi Ramayana Tbk.'},
            {'value': 'ASSA.JK', 'label': 'Adi Sarana Armada Tbk.'},
            {'value': 'ATAP.JK', 'label': 'Trimitra Prawara Goldland Tbk.'},
            {'value': 'ATIC.JK', 'label': 'Anabatic Technologies Tbk.'},
            {'value': 'AUTO.JK', 'label': 'Astra Otoparts Tbk.'},
            {'value': 'AYLS.JK', 'label': 'Agro Yasa Lestari Tbk.'},
            {'value': 'BABP.JK', 'label': 'Bank MNC Internasional Tbk.'},
            {'value': 'BACA.JK', 'label': 'Bank Capital Indonesia Tbk.'},
            {'value': 'BAJA.JK', 'label': 'Saranacentral Bajatama Tbk.'},
            {'value': 'BALI.JK', 'label': 'Bali Towerindo Sentra Tbk.'},
            {'value': 'BANK.JK', 'label': 'Bank Aladin Syariah Tbk.'},
            {'value': 'BAPA.JK', 'label': 'Bekasi Asri Pemula Tbk.'},
            {'value': 'BAPI.JK', 'label': 'Bhakti Agung Propertindo Tbk.'},
            {'value': 'BATA.JK', 'label': 'Sepatu Bata Tbk.'},
            {'value': 'BAYU.JK', 'label': 'Bayu Buana Tbk.'},
            {'value': 'BBCA.JK', 'label': 'Bank Central Asia Tbk.'},
            {'value': 'BBHI.JK', 'label': 'Allo Bank Indonesia Tbk.'},
            {'value': 'BBKP.JK', 'label': 'Bank KB Bukopin Tbk.'},
            {'value': 'BBLD.JK', 'label': 'Buana Finance Tbk.'},
            {'value': 'BBMD.JK', 'label': 'Bank Mestika Dharma Tbk.'},
            {'value': 'BBNI.JK', 'label': 'Bank Negara Indonesia (Persero) Tbk.'},
            {'value': 'BBRI.JK', 'label': 'Bank Rakyat Indonesia (Persero) Tbk.'},
            {'value': 'BBRM.JK', 'label': 'Pelayaran Nasional Bina Buana Tbk.'},
            {'value': 'BBSI.JK', 'label': 'Bank Bisnis Internasional Tbk.'},
            {'value': 'BBSS.JK', 'label': 'Bumi Benowo Sukses Sejahtera Tbk.'},
            {'value': 'BBTN.JK', 'label': 'Bank Tabungan Negara (Persero) Tbk.'},
            {'value': 'BBYB.JK', 'label': 'Bank Neo Commerce Tbk.'},
            {'value': 'BCAP.JK', 'label': 'MNC Kapital Indonesia Tbk.'},
            {'value': 'BCIC.JK', 'label': 'Bank JTrust Indonesia Tbk.'},
            {'value': 'BCIP.JK', 'label': 'Bumi Citra Permai Tbk.'},
            {'value': 'BDMN.JK', 'label': 'Bank Danamon Indonesia Tbk.'},
            {'value': 'BEBS.JK', 'label': 'Berkah Beton Sadaya Tbk.'},
            {'value': 'BEEF.JK', 'label': 'Estika Tata Tiara Tbk.'},
            {'value': 'BEKS.JK', 'label': 'Bank Pembangunan Daerah Banten Tbk.'},
            {'value': 'BELL.JK', 'label': 'Trisula Textile Industries Tbk.'},
            {'value': 'BESS.JK', 'label': 'Batulicin Nusantara Maritim Tbk.'},
            {'value': 'BEST.JK', 'label': 'Bekasi Fajar Industrial Estate Tbk.'},
            {'value': 'BFIN.JK', 'label': 'BFI Finance Indonesia Tbk.'},
            {'value': 'BGTG.JK', 'label': 'Bank Ganesha Tbk.'},
            {'value': 'BHAT.JK', 'label': 'Bhakti Multi Artha Tbk.'},
            {'value': 'BHIT.JK', 'label': 'MNC Investama Tbk.'},
            {'value': 'BIKA.JK', 'label': 'Binakarya Jaya Abadi Tbk.'},
            {'value': 'BIMA.JK', 'label': 'Primarindo Asia Infrastructure Tbk.'},
            {'value': 'BINA.JK', 'label': 'Bank Ina Perdana Tbk.'},
            {'value': 'BIPI.JK', 'label': 'Astrindo Nusantara Infrastruktur Tbk.'},
            {'value': 'BIPP.JK', 'label': 'Bhuwanatala Indah Permai Tbk.'},
            {'value': 'BIRD.JK', 'label': 'Blue Bird Tbk.'},
            {'value': 'BISI.JK', 'label': 'BISI International Tbk.'},
            {'value': 'BJBR.JK', 'label': 'Bank Pembangunan Daerah Jawa Barat Tbk.'},
            {'value': 'BJTM.JK', 'label': 'Bank Pembangunan Daerah Jawa Tengah Tbk.'},
            {'value': 'BKDP.JK', 'label': 'Bukit Darmo Property Tbk.'},
            {'value': 'BKSL.JK', 'label': 'Sentul City Tbk.'},
            {'value': 'BKSW.JK', 'label': 'Bank QNB Indonesia Tbk.'},
            {'value': 'BLTA.JK', 'label': 'Berlian Laju Tanker Tbk.'},
            {'value': 'BLTZ.JK', 'label': 'Graha Layar Prima Tbk.'},
            {'value': 'BLUE.JK', 'label': 'Berkah Prima Perkasa Tbk.'},
            {'value': 'BMAS.JK', 'label': 'Bank Maspion Indonesia Tbk.'},
            {'value': 'BMHS.JK', 'label': 'Bundamedik Tbk.'},
            {'value': 'BMRI.JK', 'label': 'Bank Mandiri (Persero) Tbk.'},
            {'value': 'BMSR.JK', 'label': 'Bintang Mitra Semestaraya Tbk.'},
            {'value': 'BMTR.JK', 'label': 'Global Mediacom Tbk.'},
            {'value': 'BNBA.JK', 'label': 'Bank Bumi Arta Tbk.'},
            {'value': 'BNBR.JK', 'label': 'Bakrie & Brothers Tbk.'},
            {'value': 'BNGA.JK', 'label': 'Bank CIMB Niaga Tbk.'},
            {'value': 'BNII.JK', 'label': 'Bank Maybank Indonesia Tbk.'},
            {'value': 'BNLI.JK', 'label': 'Bank Permata Tbk.'},
            {'value': 'BOGA.JK', 'label': 'Bintang Oto Global Tbk.'},
            {'value': 'BOLA.JK', 'label': 'Bali Bintang Sejahtera Tbk.'},
            {'value': 'BOLT.JK', 'label': 'Garuda Metalindo Tbk.'},
            {'value': 'BOSS.JK', 'label': 'Borneo Olah Sarana Sukses Tbk.'},
            {'value': 'BPFI.JK', 'label': 'Batavia Prosperindo Finance Tbk.'},
            {'value': 'BPII.JK', 'label': 'Batavia Prosperindo Internasional Tbk.'},
            {'value': 'BPTR.JK', 'label': 'Batavia Prosperindo Trans Tbk.'},
            {'value': 'BRAM.JK', 'label': 'Indo Kordsa Tbk.'},
            {'value': 'BRIS.JK', 'label': 'Bank Syariah Indonesia Tbk.'},
            {'value': 'BRMS.JK', 'label': 'Bumi Resources Minerals Tbk.'},
            {'value': 'BRNA.JK', 'label': 'Berlina Tbk.'},
            {'value': 'BRPT.JK', 'label': 'Barito Pacific Tbk.'},
            {'value': 'BSDE.JK', 'label': 'Bumi Serpong Damai Tbk.'},
            {'value': 'BSIM.JK', 'label': 'Bank Sinarmas Tbk.'},
            {'value': 'BSSR.JK', 'label': 'Baramulti Suksessarana Tbk.'},
            {'value': 'BSWD.JK', 'label': 'Bank Of India Indonesia Tbk.'},
            {'value': 'BTEK.JK', 'label': 'Bumi Teknokultura Unggul Tbk.'},
            {'value': 'BTEL.JK', 'label': 'Bakrie Telecom Tbk.'},
            {'value': 'BTON.JK', 'label': 'Betonjaya Manunggal Tbk.'},
            {'value': 'BTPN.JK', 'label': 'Bank BTPN Tbk.'},
            {'value': 'BTPS.JK', 'label': 'Bank BTPN Syariah Tbk.'},
            {'value': 'BUDI.JK', 'label': 'Budi Starch & Sweetener Tbk.'},
            {'value': 'BUKK.JK', 'label': 'Bukaka Teknik Utama Tbk.'},
            {'value': 'BULL.JK', 'label': 'Buana Lintas Lautan Tbk.'},
            {'value': 'BUMI.JK', 'label': 'Bumi Resources Tbk.'},
            {'value': 'BUVA.JK', 'label': 'Bukit Uluwatu Villa Tbk.'},
            {'value': 'BVIC.JK', 'label': 'Bank Victoria International Tbk.'},
            {'value': 'BWPT.JK', 'label': 'Eagle High Plantations Tbk.'},
            {'value': 'BYAN.JK', 'label': 'Bayan Resources Tbk.'},
            {'value': 'CAKK.JK', 'label': 'Cahayaputra Asa Keramik Tbk.'},
            {'value': 'CAMP.JK', 'label': 'Campina Ice Cream Industry Tbk.'},
            {'value': 'CANI.JK', 'label': 'Capitol Nusantara Indonesia Tbk.'},
            {'value': 'CARE.JK', 'label': 'Metro Healthcare Indonesia Tbk.'},
            {'value': 'CARS.JK', 'label': 'PT Bintraco Dharma Tbk.'},
            {'value': 'CASA.JK', 'label': 'Capital Financial Indonesia Tbk.'},
            {'value': 'CASH.JK', 'label': 'Cashlez Worldwide Indonesia Tbk.'},
            {'value': 'CASS.JK', 'label': 'Cardig Aero Services Tbk.'},
            {'value': 'CBMF.JK', 'label': 'Cahaya Bintang Medan Tbk.'},
            {'value': 'CCSI.JK', 'label': 'Communication Cable Systems Tbk.'},
            {'value': 'CEKA.JK', 'label': 'Wilmar Cahaya Indonesia Tbk.'},
            {'value': 'CENT.JK', 'label': 'Centratama Telekomunikasi Indo Tbk.'},
            {'value': 'CFIN.JK', 'label': 'Clipan Finance Indonesia Tbk.'},
            {'value': 'CINT.JK', 'label': 'Chitose Internasional Tbk.'},
            {'value': 'CITA.JK', 'label': 'Cita Mineral Investindo Tbk.'},
            {'value': 'CITY.JK', 'label': 'Natura City Developments Tbk.'},
            {'value': 'CLAY.JK', 'label': 'Citra Putra Realty Tbk.'},
            {'value': 'CLEO.JK', 'label': 'Sariguna Primatirta Tbk.'},
            {'value': 'CLPI.JK', 'label': 'Colorpak Indonesia Tbk.'},
            {'value': 'CMNP.JK', 'label': 'Citra Marga Nusaphala Persada Tbk.'},
            {'value': 'CMPP.JK', 'label': 'AirAsia Indonesia Tbk.'},
            {'value': 'CNKO.JK', 'label': 'Exploitasi Energi Indonesia Tbk.'},
            {'value': 'CNTX.JK', 'label': 'Century Textile Industry Tbk.'},
            {'value': 'COCO.JK', 'label': 'Wahana Interfood Nusantara Tbk.'},
            {'value': 'COWL.JK', 'label': 'Cowell Development Tbk.'},
            {'value': 'CPIN.JK', 'label': 'Charoen Pokphand Indonesia Tbk.'},
            {'value': 'CPRI.JK', 'label': 'Capri Nusa Satu Properti Tbk.'},
            {'value': 'CPRO.JK', 'label': 'Central Proteina Prima Tbk.'},
            {'value': 'CSAP.JK', 'label': 'Catur Sentosa Adiprana Tbk.'},
            {'value': 'CSIS.JK', 'label': 'Cahayasakti Investindo Sukses Tbk.'},
            {'value': 'CSMI.JK', 'label': 'Cipta Selera Murni Tbk.'},
            {'value': 'CSRA.JK', 'label': 'Cisadane Sawit Raya Tbk.'},
            {'value': 'CTBN.JK', 'label': 'Citra Tubindo Tbk.'},
            {'value': 'CTRA.JK', 'label': 'Ciputra Development Tbk.'},
            {'value': 'CTTH.JK', 'label': 'Citatah Tbk.'},
            {'value': 'DADA.JK', 'label': 'Diamond Citra Propertindo Tbk.'},
            {'value': 'DART.JK', 'label': 'Duta Anggada Realty Tbk.'},
            {'value': 'DAYA.JK', 'label': 'Duta Intidaya Tbk.'},
            {'value': 'DCII.JK', 'label': 'DCI Indonesia Tbk.'},
            {'value': 'DEAL.JK', 'label': 'Dewata Freightinternational Tbk.'},
            {'value': 'DEFI.JK', 'label': 'Danasupra Erapacific Tbk.'},
            {'value': 'DEWA.JK', 'label': 'Darma Henwa Tbk.'},
            {'value': 'DFAM.JK', 'label': 'Dafam Property Indonesia Tbk.'},
            {'value': 'DGIK.JK', 'label': 'Nusa Konstruksi Enjiniring Tbk.'},
            {'value': 'DGNS.JK', 'label': 'Diagnos Laboratorium Utama Tbk.'},
            {'value': 'DIGI.JK', 'label': 'Arkadia Digital Media Tbk.'},
            {'value': 'DILD.JK', 'label': 'Intiland Development Tbk.'},
            {'value': 'DIVA.JK', 'label': 'Distribusi Voucher Nusantara Tbk.'},
            {'value': 'DKFT.JK', 'label': 'Central Omega Resources Tbk.'},
            {'value': 'DLTA.JK', 'label': 'Delta Djakarta Tbk.'},
            {'value': 'DMAS.JK', 'label': 'Puradelta Lestari Tbk.'},
            {'value': 'DMMX.JK', 'label': 'Digital Mediatama Maxima Tbk.'},
            {'value': 'DMND.JK', 'label': 'Diamond Food Indonesia Tbk.'},
            {'value': 'DNAR.JK', 'label': 'Bank Oke Indonesia Tbk.'},
            {'value': 'DNET.JK', 'label': 'Indoritel Makmur Internasional Tbk.'},
            {'value': 'DOID.JK', 'label': 'Delta Dunia Makmur Tbk.'},
            {'value': 'DPNS.JK', 'label': 'Duta Pertiwi Nusantara Tbk.'},
            {'value': 'DPUM.JK', 'label': 'Dua Putra Utama Makmur Tbk.'},
            {'value': 'DSFI.JK', 'label': 'Dharma Samudera Fishing Industri Tbk.'},
            {'value': 'DSNG.JK', 'label': 'Dharma Satya Nusantara Tbk.'},
            {'value': 'DSSA.JK', 'label': 'Dian Swastatika Sentosa Tbk.'},
            {'value': 'DUCK.JK', 'label': 'Jaya Bersama Indo Tbk.'},
            {'value': 'DUTI.JK', 'label': 'Duta Pertiwi Tbk.'},
            {'value': 'DVLA.JK', 'label': 'Darya-Varia Laboratoria Tbk.'},
            {'value': 'DWGL.JK', 'label': 'Dwi Guna Laksana Tbk.'},
            {'value': 'DYAN.JK', 'label': 'Dyandra Media International Tbk.'},
            {'value': 'EAST.JK', 'label': 'Eastparc Hotel Tbk.'},
            {'value': 'ECII.JK', 'label': 'Electronic City Indonesia Tbk.'},
            {'value': 'EDGE.JK', 'label': 'Indointernet Tbk.'},
            {'value': 'EKAD.JK', 'label': 'Ekadharma International Tbk.'},
            {'value': 'ELSA.JK', 'label': 'Elnusa Tbk.'},
            {'value': 'ELTY.JK', 'label': 'Bakrieland Development Tbk.'},
            {'value': 'EMDE.JK', 'label': 'Megapolitan Developments Tbk.'},
            {'value': 'EMTK.JK', 'label': 'Elang Mahkota Teknologi Tbk.'},
            {'value': 'ENRG.JK', 'label': 'Energi Mega Persada Tbk.'},
            {'value': 'ENVY.JK', 'label': 'Envy Technologies Indonesia Tbk.'},
            {'value': 'ENZO.JK', 'label': 'Morenzo Abadi Perkasa Tbk.'},
            {'value': 'EPAC.JK', 'label': 'Megalestari Epack Sentosaraya Tbk.'},
            {'value': 'EPMT.JK', 'label': 'Enseval Putera Megatrading Tbk.'},
            {'value': 'ERAA.JK', 'label': 'Erajaya Swasembada Tbk.'},
            {'value': 'ERTX.JK', 'label': 'Eratex Djaja Tbk.'},
            {'value': 'ESIP.JK', 'label': 'Sinergi Inti Plastindo Tbk.'},
            {'value': 'ESSA.JK', 'label': 'Surya Esa Perkasa Tbk.'},
            {'value': 'ESTA.JK', 'label': 'Esta Multi Usaha Tbk.'},
            {'value': 'ESTI.JK', 'label': 'Ever Shine Tex Tbk.'},
            {'value': 'ETWA.JK', 'label': 'Eterindo Wahanatama Tbk.'},
            {'value': 'EXCL.JK', 'label': 'XL Axiata Tbk.'},
            {'value': 'FAPA.JK', 'label': 'FAP Agri Tbk.'},
            {'value': 'FAST.JK', 'label': 'Fast Food Indonesia Tbk.'},
            {'value': 'FASW.JK', 'label': 'Fajar Surya Wisesa Tbk.'},
            {'value': 'FILM.JK', 'label': 'MD Pictures Tbk.'},
            {'value': 'FIMP.JK', 'label': 'Fimperkasa Utama Tbk.'},
            {'value': 'FIRE.JK', 'label': 'Alfa Energi Investama Tbk.'},
            {'value': 'FISH.JK', 'label': 'FKS Multi Agro Tbk.'},
            {'value': 'FITT.JK', 'label': 'Hotel Fitra International Tbk.'},
            {'value': 'FLMC.JK', 'label': 'Falmaco Nonwoven Industri Tbk.'},
            {'value': 'FMII.JK', 'label': 'Fortune Mate Indonesia Tbk.'},
            {'value': 'FOOD.JK', 'label': 'Sentra Food Indonesia Tbk.'},
            {'value': 'FORU.JK', 'label': 'Fortune Indonesia Tbk.'},
            {'value': 'FORZ.JK', 'label': 'Forza Land Indonesia Tbk.'},
            {'value': 'FPNI.JK', 'label': 'Lotte Chemical Titan Tbk.'},
            {'value': 'FREN.JK', 'label': 'Smartfren Telecom Tbk.'},
            {'value': 'FUJI.JK', 'label': 'Fuji Finance Indonesia Tbk.'},
            {'value': 'GAMA.JK', 'label': 'Aksara Global Development Tbk.'},
            {'value': 'GDST.JK', 'label': 'Gunawan Dianjaya Steel Tbk.'},
            {'value': 'GDYR.JK', 'label': 'Goodyear Indonesia Tbk.'},
            {'value': 'GEMA.JK', 'label': 'Gema Grahasarana Tbk.'},
            {'value': 'GEMS.JK', 'label': 'Golden Energy Mines Tbk.'},
            {'value': 'GGRM.JK', 'label': 'Gudang Garam Tbk.'},
            {'value': 'GGRP.JK', 'label': 'Gunung Raja Paksi Tbk.'},
            {'value': 'GHON.JK', 'label': 'Gihon Telekomunikasi Indonesia Tbk.'},
            {'value': 'GIAA.JK', 'label': 'Garuda Indonesia (Persero) Tbk.'},
            {'value': 'GJTL.JK', 'label': 'Gajah Tunggal Tbk.'},
            {'value': 'GLOB.JK', 'label': 'Globe Kita Terang Tbk.'},
            {'value': 'GLVA.JK', 'label': 'Galva Technologies Tbk.'},
            {'value': 'GMFI.JK', 'label': 'Garuda Maintenance Facility Ae Tbk.'},
            {'value': 'GMTD.JK', 'label': 'Gowa Makassar Tourism Development Tbk.'},
            {'value': 'GOLD.JK', 'label': 'Visi Telekomunikasi Infrastruktur Tbk.'},
            {'value': 'GOLL.JK', 'label': 'Golden Plantation Tbk.'},
            {'value': 'GOOD.JK', 'label': 'Garudafood Putra Putri Jaya Tbk.'},
            {'value': 'GPRA.JK', 'label': 'Perdana Gapuraprima Tbk.'},
            {'value': 'GSMF.JK', 'label': 'Equity Development Investment Tbk.'},
            {'value': 'GTBO.JK', 'label': 'Garda Tujuh Buana Tbk.'},
            {'value': 'GWSA.JK', 'label': 'Greenwood Sejahtera Tbk.'},
            {'value': 'GZCO.JK', 'label': 'Gozco Plantations Tbk.'},
            {'value': 'HADE.JK', 'label': 'Himalaya Energi Perkasa Tbk.'},
            {'value': 'HDFA.JK', 'label': 'Radana Bhaskara Finance Tbk.'},
            {'value': 'HDIT.JK', 'label': 'Hensel Davest Indonesia Tbk.'},
            {'value': 'HDTX.JK', 'label': 'Panasia Indo Resources Tbk.'},
            {'value': 'HEAL.JK', 'label': 'Medikaloka Hermina Tbk.'},
            {'value': 'HELI.JK', 'label': 'Jaya Trishindo Tbk.'},
            {'value': 'HERO.JK', 'label': 'Hero Supermarket Tbk.'},
            {'value': 'HEXA.JK', 'label': 'Hexindo Adiperkasa Tbk.'},
            {'value': 'HITS.JK', 'label': 'Humpuss Intermoda Transportasi Tbk.'},
            {'value': 'HKMU.JK', 'label': 'HK Metals Utama Tbk.'},
            {'value': 'HMSP.JK', 'label': 'H.M. Sampoerna Tbk.'},
            {'value': 'HOKI.JK', 'label': 'Buyung Poetra Sembada Tbk.'},
            {'value': 'HOME.JK', 'label': 'Hotel Mandarine Regency Tbk.'},
            {'value': 'HOMI.JK', 'label': 'Grand House Mulia Tbk.'},
            {'value': 'HOPE.JK', 'label': 'Harapan Duta Pertiwi Tbk.'},
            {'value': 'HOTL.JK', 'label': 'Saraswati Griya Lestari Tbk.'},
            {'value': 'HRME.JK', 'label': 'Menteng Heritage Realty Tbk.'},
            {'value': 'HRTA.JK', 'label': 'Hartadinata Abadi Tbk.'},
            {'value': 'HRUM.JK', 'label': 'Harum Energy Tbk.'},
            {'value': 'IATA.JK', 'label': 'Indonesia Transport & Infrastruktur Tbk.'},
            {'value': 'IBFN.JK', 'label': 'Intan Baruprana Finance Tbk.'},
            {'value': 'IBST.JK', 'label': 'Inti Bangun Sejahtera Tbk.'},
            {'value': 'ICBP.JK', 'label': 'Indofood CBP Sukses Makmur Tbk.'},
            {'value': 'ICON.JK', 'label': 'Island Concepts Indonesia Tbk.'},
            {'value': 'IDPR.JK', 'label': 'Indonesia Pondasi Raya Tbk.'},
            {'value': 'IFII.JK', 'label': 'Indonesia Fibreboard Industry Tbk.'},
            {'value': 'IFSH.JK', 'label': 'Ifishdeco Tbk.'},
            {'value': 'IGAR.JK', 'label': 'Champion Pacific Indonesia Tbk.'},
            {'value': 'IIKP.JK', 'label': 'Inti Agri Resources Tbk.'},
            {'value': 'IKAI.JK', 'label': 'Intikeramik Alamasri Industri Tbk.'},
            {'value': 'IKAN.JK', 'label': 'Era Mandiri Cemerlang Tbk.'},
            {'value': 'IKBI.JK', 'label': 'Sumi Indo Kabel Tbk.'},
            {'value': 'IMAS.JK', 'label': 'Indomobil Sukses Internasional Tbk.'},
            {'value': 'IMJS.JK', 'label': 'Indomobil Multi Jasa Tbk.'},
            {'value': 'IMPC.JK', 'label': 'Impack Pratama Industri Tbk.'},
            {'value': 'INAF.JK', 'label': 'Indofarma Tbk.'},
            {'value': 'INAI.JK', 'label': 'Indal Aluminium Industry Tbk.'},
            {'value': 'INCF.JK', 'label': 'Indo Komoditi Korpora Tbk.'},
            {'value': 'INCI.JK', 'label': 'Intanwijaya Internasional Tbk.'},
            {'value': 'INCO.JK', 'label': 'Vale Indonesia Tbk.'},
            {'value': 'INDF.JK', 'label': 'Indofood Sukses Makmur Tbk.'},
            {'value': 'INDO.JK', 'label': 'Royalindo Investa Wijaya Tbk.'},
            {'value': 'INDR.JK', 'label': 'Indo-Rama Synthetics Tbk.'},
            {'value': 'INDS.JK', 'label': 'Indospring Tbk.'},
            {'value': 'INDX.JK', 'label': 'Tanah Laut Tbk.'},
            {'value': 'INDY.JK', 'label': 'Indika Energy Tbk.'},
            {'value': 'INKP.JK', 'label': 'Indah Kiat Pulp & Paper Tbk.'},
            {'value': 'INOV.JK', 'label': 'Inocycle Technology Group Tbk.'},
            {'value': 'INPC.JK', 'label': 'Bank Artha Graha Internasional Tbk.'},
            {'value': 'INPP.JK', 'label': 'Indonesian Paradise Property Tbk.'},
            {'value': 'INPS.JK', 'label': 'Indah Prakasa Sentosa Tbk.'},
            {'value': 'INRU.JK', 'label': 'Toba Pulp Lestari Tbk.'},
            {'value': 'INTA.JK', 'label': 'Intraco Penta Tbk.'},
            {'value': 'INTD.JK', 'label': 'Inter Delta Tbk.'},
            {'value': 'INTP.JK', 'label': 'Indocement Tunggal Prakarsa Tbk.'},
            {'value': 'IPAC.JK', 'label': 'Era Graharealty Tbk.'},
            {'value': 'IPCC.JK', 'label': 'Indonesia Kendaraan Terminal Tbk.'},
            {'value': 'IPCM.JK', 'label': 'Jasa Armada Indonesia Tbk.'},
            {'value': 'IPOL.JK', 'label': 'Indopoly Swakarsa Industry Tbk.'},
            {'value': 'IPTV.JK', 'label': 'MNC Vision Networks Tbk.'},
            {'value': 'IRRA.JK', 'label': 'Itama Ranoraya Tbk.'},
            {'value': 'ISAT.JK', 'label': 'Indosat Tbk.'},
            {'value': 'ISSP.JK', 'label': 'Steel Pipe Industry of Indonesia Tbk.'},
            {'value': 'ITIC.JK', 'label': 'Indonesian Tobacco Tbk.'},
            {'value': 'ITMA.JK', 'label': 'Sumber Energi Andalan Tbk.'},
            {'value': 'ITMG.JK', 'label': 'Indo Tambangraya Megah Tbk.'},
            {'value': 'JAST.JK', 'label': 'Jasnita Telekomindo Tbk.'},
            {'value': 'JAWA.JK', 'label': 'Jaya Agra Wattie Tbk.'},
            {'value': 'JAYA.JK', 'label': 'Armada Berjaya Trans Tbk.'},
            {'value': 'JECC.JK', 'label': 'Jembo Cable Company Tbk.'},
            {'value': 'JGLE.JK', 'label': 'Graha Andrasentra Propertindo Tbk.'},
            {'value': 'JIHD.JK', 'label': 'Jakarta International Hotels Tbk.'},
            {'value': 'JKON.JK', 'label': 'Jaya Konstruksi Manggala Prata Tbk.'},
            {'value': 'JKSW.JK', 'label': 'Jakarta Kyoei Steel Works Tbk.'},
            {'value': 'JMAS.JK', 'label': 'Asuransi Jiwa Syariah Jasa Mit Tbk.'},
            {'value': 'JPFA.JK', 'label': 'Japfa Comfeed Indonesia Tbk.'},
            {'value': 'JRPT.JK', 'label': 'Jaya Real Property Tbk.'},
            {'value': 'JSKY.JK', 'label': 'Sky Energy Indonesia Tbk.'},
            {'value': 'JSMR.JK', 'label': 'Jasa Marga (Persero) Tbk.'},
            {'value': 'JSPT.JK', 'label': 'Jakarta Setiabudi Internasiona Tbk.'},
            {'value': 'JTPE.JK', 'label': 'Jasuindo Tiga Perkasa Tbk.'},
            {'value': 'KAEF.JK', 'label': 'Kimia Farma Tbk.'},
            {'value': 'KARW.JK', 'label': 'ICTSI Jasa Prima Tbk.'},
            {'value': 'KAYU.JK', 'label': 'Darmi Bersaudara Tbk.'},
            {'value': 'KBAG.JK', 'label': 'Karya Bersama Anugerah Tbk.'},
            {'value': 'KBLI.JK', 'label': 'KMI Wire & Cable Tbk.'},
            {'value': 'KBLM.JK', 'label': 'Kabelindo Murni Tbk.'},
            {'value': 'KBLV.JK', 'label': 'First Media Tbk.'},
            {'value': 'KBRI.JK', 'label': 'Kertas Basuki Rachmat Indonesia Tbk.'},
            {'value': 'KDSI.JK', 'label': 'Kedawung Setia Industrial Tbk.'},
            {'value': 'KEEN.JK', 'label': 'Kencana Energi Lestari Tbk.'},
            {'value': 'KEJU.JK', 'label': 'Mulia Boga Raya Tbk.'},
            {'value': 'KIAS.JK', 'label': 'Keramika Indonesia Assosiasi Tbk.'},
            {'value': 'KICI.JK', 'label': 'Kedaung Indah Can Tbk.'},
            {'value': 'KIJA.JK', 'label': 'Kawasan Industri Jababeka Tbk.'},
            {'value': 'KINO.JK', 'label': 'Kino Indonesia Tbk.'},
            {'value': 'KIOS.JK', 'label': 'Kioson Komersial Indonesia Tbk.'},
            {'value': 'KJEN.JK', 'label': 'Krida Jaringan Nusantara Tbk.'},
            {'value': 'KKGI.JK', 'label': 'Resource Alam Indonesia Tbk.'},
            {'value': 'KLBF.JK', 'label': 'Kalbe Farma Tbk.'},
            {'value': 'KMDS.JK', 'label': 'Kurniamitra Duta Sentosa Tbk.'},
            {'value': 'KMTR.JK', 'label': 'Kirana Megatara Tbk.'},
            {'value': 'KOBX.JK', 'label': 'Kobexindo Tractors Tbk.'},
            {'value': 'KOIN.JK', 'label': 'Kokoh Inti Arebama Tbk.'},
            {'value': 'KONI.JK', 'label': 'Perdana Bangun Pusaka Tbk.'},
            {'value': 'KOPI.JK', 'label': 'Mitra Energi Persada Tbk.'},
            {'value': 'KOTA.JK', 'label': 'DMS Propertindo Tbk.'},
            {'value': 'KPAL.JK', 'label': 'Steadfast Marine Tbk.'},
            {'value': 'KPAS.JK', 'label': 'Cottonindo Ariesta Tbk.'},
            {'value': 'KPIG.JK', 'label': 'MNC Land Tbk.'},
            {'value': 'KRAH.JK', 'label': 'Grand Kartech Tbk.'},
            {'value': 'KRAS.JK', 'label': 'Krakatau Steel (Persero) Tbk.'},
            {'value': 'KREN.JK', 'label': 'Kresna Graha Investama Tbk.'},
            {'value': 'LABA.JK', 'label': 'Ladangbaja Murni Tbk.'},
            {'value': 'LAND.JK', 'label': 'Trimitra Propertindo Tbk.'},
            {'value': 'LAPD.JK', 'label': 'Leyand International Tbk.'},
            {'value': 'LCGP.JK', 'label': 'Eureka Prima Jakarta Tbk.'},
            {'value': 'LCKM.JK', 'label': 'LCK Global Kedaton Tbk.'},
            {'value': 'LEAD.JK', 'label': 'Logindo Samudramakmur Tbk.'},
            {'value': 'LFLO.JK', 'label': 'Imago Mulia Persada Tbk.'},
            {'value': 'LIFE.JK', 'label': 'Asuransi Jiwa Sinarmas MSIG Tbk.'},
            {'value': 'LINK.JK', 'label': 'Link Net Tbk.'},
            {'value': 'LION.JK', 'label': 'Lion Metal Works Tbk.'},
            {'value': 'LMAS.JK', 'label': 'Limas Indonesia Makmur Tbk.'},
            {'value': 'LMPI.JK', 'label': 'Langgeng Makmur Industri Tbk.'},
            {'value': 'LMSH.JK', 'label': 'Lionmesh Prima Tbk.'},
            {'value': 'LPCK.JK', 'label': 'Lippo Cikarang Tbk.'},
            {'value': 'LPGI.JK', 'label': 'Lippo General Insurance Tbk.'},
            {'value': 'LPIN.JK', 'label': 'Multi Prima Sejahtera Tbk.'},
            {'value': 'LPKR.JK', 'label': 'Lippo Karawaci Tbk.'},
            {'value': 'LPLI.JK', 'label': 'Star Pacific Tbk.'},
            {'value': 'LPPF.JK', 'label': 'Matahari Department Store Tbk.'},
            {'value': 'LPPS.JK', 'label': 'Lenox Pasifik Investama Tbk.'},
            {'value': 'LRNA.JK', 'label': 'Eka Sari Lorena Transport Tbk.'},
            {'value': 'LSIP.JK', 'label': 'PP London Sumatra Indonesia Tbk.'},
            {'value': 'LTLS.JK', 'label': 'Lautan Luas Tbk.'},
            {'value': 'LUCK.JK', 'label': 'Sentral Mitra Informatika Tbk.'},
            {'value': 'LUCY.JK', 'label': 'Lima Dua Lima Tiga Tbk.'},
            {'value': 'MABA.JK', 'label': 'Marga Abhinaya Abadi Tbk.'},
            {'value': 'MAGP.JK', 'label': 'Multi Agro Gemilang Plantation Tbk.'},
            {'value': 'MAIN.JK', 'label': 'Malindo Feedmill Tbk.'},
            {'value': 'MAMI.JK', 'label': 'Mas Murni Indonesia Tbk.'},
            {'value': 'MAPA.JK', 'label': 'Map Aktif Adiperkasa Tbk.'},
            {'value': 'MAPB.JK', 'label': 'MAP Boga Adiperkasa Tbk.'},
            {'value': 'MAPI.JK', 'label': 'Mitra Adiperkasa Tbk.'},
            {'value': 'MARI.JK', 'label': 'Mahaka Radio Integra Tbk.'},
            {'value': 'MARK.JK', 'label': 'Mark Dynamics Indonesia Tbk.'},
            {'value': 'MASA.JK', 'label': 'Multistrada Arah Sarana Tbk.'},
            {'value': 'MASB.JK', 'label': 'Bank Multiarta Sentosa Tbk.'},
            {'value': 'MAYA.JK', 'label': 'Bank Mayapada Internasional Tbk.'},
            {'value': 'MBAP.JK', 'label': 'Mitrabara Adiperdana Tbk.'},
            {'value': 'MBSS.JK', 'label': 'Mitrabahtera Segara Sejati Tbk.'},
            {'value': 'MBTO.JK', 'label': 'Martina Berto Tbk.'},
            {'value': 'MCAS.JK', 'label': 'M Cash Integrasi Tbk.'},
            {'value': 'MCOR.JK', 'label': 'Bank China Construction Bank I Tbk.'},
            {'value': 'MDIA.JK', 'label': 'Intermedia Capital Tbk.'},
            {'value': 'MDKA.JK', 'label': 'Merdeka Copper Gold Tbk.'},
            {'value': 'MDKI.JK', 'label': 'Emdeki Utama Tbk.'},
            {'value': 'MDLN.JK', 'label': 'Modernland Realty Tbk.'},
            {'value': 'MDRN.JK', 'label': 'Modern Internasional Tbk.'},
            {'value': 'MEDC.JK', 'label': 'Medco Energi Internasional Tbk.'},
            {'value': 'MEGA.JK', 'label': 'Bank Mega Tbk.'},
            {'value': 'MERK.JK', 'label': 'Merck Tbk.'},
            {'value': 'META.JK', 'label': 'Nusantara Infrastructure Tbk.'},
            {'value': 'MFIN.JK', 'label': 'Mandala Multifinance Tbk.'},
            {'value': 'MFMI.JK', 'label': 'Multifiling Mitra Indonesia Tbk.'},
            {'value': 'MGLV.JK', 'label': 'Panca Anugrah Wisesa Tbk.'},
            {'value': 'MGNA.JK', 'label': 'Magna Investama Mandiri Tbk.'},
            {'value': 'MGRO.JK', 'label': 'Mahkota Group Tbk.'},
            {'value': 'MICE.JK', 'label': 'Multi Indocitra Tbk.'},
            {'value': 'MIDI.JK', 'label': 'Midi Utama Indonesia Tbk.'},
            {'value': 'MIKA.JK', 'label': 'Mitra Keluarga Karyasehat Tbk.'},
            {'value': 'MINA.JK', 'label': 'Sanurhasta Mitra Tbk.'},
            {'value': 'MIRA.JK', 'label': 'Mitra International Resources Tbk.'},
            {'value': 'MITI.JK', 'label': 'Mitra Investindo Tbk.'},
            {'value': 'MKNT.JK', 'label': 'Mitra Komunikasi Nusantara Tbk.'},
            {'value': 'MKPI.JK', 'label': 'Metropolitan Kentjana Tbk.'},
            {'value': 'MLBI.JK', 'label': 'Multi Bintang Indonesia Tbk.'},
            {'value': 'MLIA.JK', 'label': 'Mulia Industrindo Tbk.'},
            {'value': 'MLPL.JK', 'label': 'Multipolar Tbk.'},
            {'value': 'MLPT.JK', 'label': 'Multipolar Technology Tbk.'},
            {'value': 'MMLP.JK', 'label': 'Mega Manunggal Property Tbk.'},
            {'value': 'MNCN.JK', 'label': 'Media Nusantara Citra Tbk.'},
            {'value': 'MOLI.JK', 'label': 'Madusari Murni Indah Tbk.'},
            {'value': 'MPMX.JK', 'label': 'Mitra Pinasthika Mustika Tbk.'},
            {'value': 'MPOW.JK', 'label': 'Megapower Makmur Tbk.'},
            {'value': 'MPPA.JK', 'label': 'Matahari Putra Prima Tbk.'},
            {'value': 'MPRO.JK', 'label': 'Maha Properti Indonesia Tbk.'},
            {'value': 'MRAT.JK', 'label': 'Mustika Ratu Tbk.'},
            {'value': 'MREI.JK', 'label': 'Maskapai Reasuransi Indonesia Tbk.'},
            {'value': 'MSIN.JK', 'label': 'MNC Studios International Tbk.'},
            {'value': 'MSKY.JK', 'label': 'MNC Sky Vision Tbk.'},
            {'value': 'MTDL.JK', 'label': 'Metrodata Electronics Tbk.'},
            {'value': 'MTFN.JK', 'label': 'Capitalinc Investment Tbk.'},
            {'value': 'MTLA.JK', 'label': 'Metropolitan Land Tbk.'},
            {'value': 'MTPS.JK', 'label': 'Meta Epsi Tbk.'},
            {'value': 'MTRA.JK', 'label': 'Mitra Pemuda Tbk.'},
            {'value': 'MTSM.JK', 'label': 'Metro Realty Tbk.'},
            {'value': 'MTWI.JK', 'label': 'Malacca Trust Wuwungan Insuran Tbk.'},
            {'value': 'MYOH.JK', 'label': 'Samindo Resources Tbk.'},
            {'value': 'MYOR.JK', 'label': 'Mayora Indah Tbk.'},
            {'value': 'MYRX.JK', 'label': 'Hanson International Tbk.'},
            {'value': 'MYTX.JK', 'label': 'Asia Pacific Investama Tbk.'},
            {'value': 'NASA.JK', 'label': 'Andalan Perkasa Abadi Tbk.'},
            {'value': 'NATO.JK', 'label': 'Surya Permata Andalan Tbk.'},
            {'value': 'NELY.JK', 'label': 'Pelayaran Nelly Dwi Putri Tbk.'},
            {'value': 'NFCX.JK', 'label': 'NFC Indonesia Tbk.'},
            {'value': 'NICK.JK', 'label': 'Charnic Capital Tbk.'},
            {'value': 'NICL.JK', 'label': 'PAM Mineral Tbk.'},
            {'value': 'NIKL.JK', 'label': 'Pelat Timah Nusantara Tbk.'},
            {'value': 'NIPS.JK', 'label': 'Nipress Tbk.'},
            {'value': 'NIRO.JK', 'label': 'City Retail Developments Tbk.'},
            {'value': 'NISP.JK', 'label': 'Bank OCBC NISP Tbk.'},
            {'value': 'NOBU.JK', 'label': 'Bank Nationalnobu Tbk.'},
            {'value': 'NPGF.JK', 'label': 'Nusa Palapa Gemilang Tbk.'},
            {'value': 'NRCA.JK', 'label': 'Nusa Raya Cipta Tbk.'},
            {'value': 'NUSA.JK', 'label': 'Sinergi Megah Internusa Tbk.'},
            {'value': 'NZIA.JK', 'label': 'Nusantara Almazia Tbk.'},
            {'value': 'OASA.JK', 'label': 'Protech Mitra Perkasa Tbk.'},
            {'value': 'OCAP.JK', 'label': 'Onix Capital Tbk.'},
            {'value': 'OKAS.JK', 'label': 'Ancora Indonesia Resources Tbk.'},
            {'value': 'OMRE.JK', 'label': 'Indonesia Prima Property Tbk.'},
            {'value': 'OPMS.JK', 'label': 'Optima Prima Metal Sinergi Tbk.'},
            {'value': 'PADI.JK', 'label': 'Minna Padi Investama Sekuritas Tbk.'},
            {'value': 'PALM.JK', 'label': 'Provident Agro Tbk.'},
            {'value': 'PAMG.JK', 'label': 'Bima Sakti Pertiwi Tbk.'},
            {'value': 'PANI.JK', 'label': 'Pratama Abadi Nusa Industri Tbk.'},
            {'value': 'PANR.JK', 'label': 'Panorama Sentrawisata Tbk.'},
            {'value': 'PANS.JK', 'label': 'Panin Sekuritas Tbk.'},
            {'value': 'PBID.JK', 'label': 'Panca Budi Idaman Tbk.'},
            {'value': 'PBRX.JK', 'label': 'Pan Brothers Tbk.'},
            {'value': 'PBSA.JK', 'label': 'Paramita Bangun Sarana Tbk.'},
            {'value': 'PCAR.JK', 'label': 'Prima Cakrawala Abadi Tbk.'},
            {'value': 'PDES.JK', 'label': 'Destinasi Tirta Nusantara Tbk.'},
            {'value': 'PEGE.JK', 'label': 'Panca Global Kapital Tbk.'},
            {'value': 'PEHA.JK', 'label': 'Phapros Tbk.'},
            {'value': 'PGAS.JK', 'label': 'Perusahaan Gas Negara Tbk.'},
            {'value': 'PGJO.JK', 'label': 'Tourindo Guide Indonesia Tbk.'},
            {'value': 'PGLI.JK', 'label': 'Pembangunan Graha Lestari Inda Tbk.'},
            {'value': 'PGUN.JK', 'label': 'Pradiksi Gunatama Tbk.'},
            {'value': 'PICO.JK', 'label': 'Pelangi Indah Canindo Tbk.'},
            {'value': 'PJAA.JK', 'label': 'Pembangunan Jaya Ancol Tbk.'},
            {'value': 'PKPK.JK', 'label': 'Perdana Karya Perkasa Tbk.'},
            {'value': 'PLAN.JK', 'label': 'Planet Properindo Jaya Tbk.'},
            {'value': 'PLAS.JK', 'label': 'Polaris Investama Tbk.'},
            {'value': 'PLIN.JK', 'label': 'Plaza Indonesia Realty Tbk.'},
            {'value': 'PMJS.JK', 'label': 'Putra Mandiri Jembar Tbk.'},
            {'value': 'PMMP.JK', 'label': 'Panca Mitra Multiperdana Tbk.'},
            {'value': 'PNBN.JK', 'label': 'Bank Pan Indonesia Tbk.'},
            {'value': 'PNBS.JK', 'label': 'Bank Panin Dubai Syariah Tbk.'},
            {'value': 'PNGO.JK', 'label': 'Pinago Utama Tbk.'},
            {'value': 'PNIN.JK', 'label': 'Paninvest Tbk.'},
            {'value': 'PNLF.JK', 'label': 'Panin Financial Tbk.'},
            {'value': 'PNSE.JK', 'label': 'Pudjiadi & Sons Tbk.'},
            {'value': 'POLA.JK', 'label': 'Pool Advista Finance Tbk.'},
            {'value': 'POLI.JK', 'label': 'Pollux Investasi Internasional Tbk.'},
            {'value': 'POLL.JK', 'label': 'Pollux Properti Indonesia Tbk.'},
            {'value': 'POLU.JK', 'label': 'Golden Flower Tbk.'},
            {'value': 'POLY.JK', 'label': 'Asia Pacific Fibers Tbk.'},
            {'value': 'POOL.JK', 'label': 'Pool Advista Indonesia Tbk.'},
            {'value': 'PORT.JK', 'label': 'Nusantara Pelabuhan Handal Tbk.'},
            {'value': 'POSA.JK', 'label': 'Bliss Properti Indonesia Tbk.'},
            {'value': 'POWR.JK', 'label': 'Cikarang Listrindo Tbk.'},
            {'value': 'PPGL.JK', 'label': 'Prima Globalindo Logistik Tbk.'},
            {'value': 'PPRE.JK', 'label': 'PP Presisi Tbk.'},
            {'value': 'PPRO.JK', 'label': 'PP Properti Tbk.'},
            {'value': 'PRAS.JK', 'label': 'Prima Alloy Steel Universal Tbk.'},
            {'value': 'PRDA.JK', 'label': 'Prodia Widyahusada Tbk.'},
            {'value': 'PRIM.JK', 'label': 'Royal Prima Tbk.'},
            {'value': 'PSAB.JK', 'label': 'J Resources Asia Pasifik Tbk.'},
            {'value': 'PSDN.JK', 'label': 'Prasidha Aneka Niaga Tbk.'},
            {'value': 'PSGO.JK', 'label': 'Palma Serasih Tbk.'},
            {'value': 'PSKT.JK', 'label': 'Red Planet Indonesia Tbk.'},
            {'value': 'PSSI.JK', 'label': 'Pelita Samudera Shipping Tbk.'},
            {'value': 'PTBA.JK', 'label': 'Bukit Asam Tbk.'},
            {'value': 'PTDU.JK', 'label': 'Djasa Ubersakti Tbk.'},
            {'value': 'PTIS.JK', 'label': 'Indo Straits Tbk.'},
            {'value': 'PTPP.JK', 'label': 'PP (Persero) Tbk.'},
            {'value': 'PTPW.JK', 'label': 'Pratama Widya Tbk.'},
            {'value': 'PTRO.JK', 'label': 'Petrosea Tbk.'},
            {'value': 'PTSN.JK', 'label': 'Sat Nusapersada Tbk.'},
            {'value': 'PTSP.JK', 'label': 'Pioneerindo Gourmet International Tbk.'},
            {'value': 'PUDP.JK', 'label': 'Pudjiadi Prestige Tbk.'},
            {'value': 'PURA.JK', 'label': 'Putra Rajawali Kencana Tbk.'},
            {'value': 'PURE.JK', 'label': 'Trinitan Metals and Minerals Tbk.'},
            {'value': 'PURI.JK', 'label': 'Puri Global Sukses Tbk.'},
            {'value': 'PWON.JK', 'label': 'Pakuwon Jati Tbk.'},
            {'value': 'PYFA.JK', 'label': 'Pyridam Farma Tbk.'},
            {'value': 'PZZA.JK', 'label': 'Sarimelati Kencana Tbk.'},
            {'value': 'RAJA.JK', 'label': 'Rukun Raharja Tbk.'},
            {'value': 'RALS.JK', 'label': 'Ramayana Lestari Sentosa Tbk.'},
            {'value': 'RANC.JK', 'label': 'Supra Boga Lestari Tbk.'},
            {'value': 'RBMS.JK', 'label': 'Ristia Bintang Mahkotasejati Tbk.'},
            {'value': 'RDTX.JK', 'label': 'Roda Vivatex Tbk.'},
            {'value': 'REAL.JK', 'label': 'Repower Asia Indonesia Tbk.'},
            {'value': 'RELI.JK', 'label': 'Reliance Sekuritas Indonesia Tbk.'},
            {'value': 'RICY.JK', 'label': 'Ricky Putra Globalindo Tbk.'},
            {'value': 'RIGS.JK', 'label': 'Rig Tenders Indonesia Tbk.'},
            {'value': 'RIMO.JK', 'label': 'Rimo International Lestari Tbk.'},
            {'value': 'RISE.JK', 'label': 'Jaya Sukses Makmur Sentosa Tbk.'},
            {'value': 'RMBA.JK', 'label': 'Bentoel Internasional Investam Tbk.'},
            {'value': 'ROCK.JK', 'label': 'Rockfields Properti Indonesia Tbk.'},
            {'value': 'RODA.JK', 'label': 'Pikko Land Development Tbk.'},
            {'value': 'RONY.JK', 'label': 'Aesler Grup Internasional Tbk.'},
            {'value': 'ROTI.JK', 'label': 'Nippon Indosari Corpindo Tbk.'},
            {'value': 'RUIS.JK', 'label': 'Radiant Utama Interinsco Tbk.'},
            {'value': 'SAFE.JK', 'label': 'Steady Safe Tbk.'},
            {'value': 'SAME.JK', 'label': 'Sarana Meditama Metropolitan Tbk.'},
            {'value': 'SAMF.JK', 'label': 'Saraswanti Anugerah Makmur Tbk.'},
            {'value': 'SAPX.JK', 'label': 'Satria Antaran Prima Tbk.'},
            {'value': 'SATU.JK', 'label': 'Kota Satu Properti Tbk.'},
            {'value': 'SBAT.JK', 'label': 'Sejahtera Bintang Abadi Textil Tbk.'},
            {'value': 'SCCO.JK', 'label': 'Supreme Cable Manufacturing Tbk.'},
            {'value': 'SCMA.JK', 'label': 'Surya Citra Media Tbk.'},
            {'value': 'SCNP.JK', 'label': 'Selaras Citra Nusantara Perkas Tbk.'},
            {'value': 'SCPI.JK', 'label': 'Organon Pharma Indonesia Tbk.'},
            {'value': 'SDMU.JK', 'label': 'Sidomulyo Selaras Tbk.'},
            {'value': 'SDPC.JK', 'label': 'Millennium Pharmacon Internati Tbk.'},
            {'value': 'SDRA.JK', 'label': 'Bank Woori Saudara Indonesia 1 Tbk.'},
            {'value': 'SFAN.JK', 'label': 'Surya Fajar Capital Tbk.'},
            {'value': 'SGER.JK', 'label': 'Sumber Global Energy Tbk.'},
            {'value': 'SGRO.JK', 'label': 'Sampoerna Agro Tbk.'},
            {'value': 'SHID.JK', 'label': 'Hotel Sahid Jaya International Tbk.'},
            {'value': 'SHIP.JK', 'label': 'Sillo Maritime Perdana Tbk.'},
            {'value': 'SIDO.JK', 'label': 'Industri Jamu dan Farmasi Sido Tbk.'},
            {'value': 'SILO.JK', 'label': 'Siloam International Hospitals Tbk.'},
            {'value': 'SIMA.JK', 'label': 'Siwani Makmur Tbk.'},
            {'value': 'SIMP.JK', 'label': 'Salim Ivomas Pratama Tbk.'},
            {'value': 'SINI.JK', 'label': 'Singaraja Putra Tbk.'},
            {'value': 'SIPD.JK', 'label': 'Sreeya Sewu Indonesia Tbk.'},
            {'value': 'SKBM.JK', 'label': 'Sekar Bumi Tbk.'},
            {'value': 'SKLT.JK', 'label': 'Sekar Laut Tbk.'},
            {'value': 'SKRN.JK', 'label': 'Superkrane Mitra Utama Tbk.'},
            {'value': 'SKYB.JK', 'label': 'Northcliff Citranusa Indonesia Tbk.'},
            {'value': 'SLIS.JK', 'label': 'Gaya Abadi Sempurna Tbk.'},
            {'value': 'SMAR.JK', 'label': 'Smart Tbk.'},
            {'value': 'SMBR.JK', 'label': 'Semen Baturaja (Persero) Tbk.'},
            {'value': 'SMCB.JK', 'label': 'Solusi Bangun Indonesia Tbk.'},
            {'value': 'SMDM.JK', 'label': 'Suryamas Dutamakmur Tbk.'},
            {'value': 'SMDR.JK', 'label': 'Samudera Indonesia Tbk.'},
            {'value': 'SMGR.JK', 'label': 'Semen Indonesia (Persero) Tbk.'},
            {'value': 'SMKL.JK', 'label': 'Satyamitra Kemas Lestari Tbk.'},
            {'value': 'SMMA.JK', 'label': 'Sinarmas Multiartha Tbk.'},
            {'value': 'SMMT.JK', 'label': 'Golden Eagle Energy Tbk.'},
            {'value': 'SMRA.JK', 'label': 'Summarecon Agung Tbk.'},
            {'value': 'SMRU.JK', 'label': 'SMR Utama Tbk.'},
            {'value': 'SMSM.JK', 'label': 'Selamat Sempurna Tbk.'},
            {'value': 'SNLK.JK', 'label': 'Sunter Lakeside Hotel Tbk.'},
            {'value': 'SOCI.JK', 'label': 'Soechi Lines Tbk.'},
            {'value': 'SOFA.JK', 'label': 'Boston Furniture Industries Tbk.'},
            {'value': 'SOHO.JK', 'label': 'Soho Global Health Tbk.'},
            {'value': 'SONA.JK', 'label': 'Sona Topas Tourism Industry Tbk.'},
            {'value': 'SOSS.JK', 'label': 'Shield On Service Tbk.'},
            {'value': 'SOTS.JK', 'label': 'Satria Mega Kencana Tbk.'},
            {'value': 'SPMA.JK', 'label': 'Suparma Tbk.'},
            {'value': 'SPTO.JK', 'label': 'Surya Pertiwi Tbk.'},
            {'value': 'SQMI.JK', 'label': 'Wilton Makmur Indonesia Tbk.'},
            {'value': 'SRAJ.JK', 'label': 'Sejahteraraya Anugrahjaya Tbk.'},
            {'value': 'SRIL.JK', 'label': 'Sri Rejeki Isman Tbk.'},
            {'value': 'SRSN.JK', 'label': 'Indo Acidatama Tbk.'},
            {'value': 'SRTG.JK', 'label': 'Saratoga Investama Sedaya Tbk.'},
            {'value': 'SSIA.JK', 'label': 'Surya Semesta Internusa Tbk.'},
            {'value': 'SSMS.JK', 'label': 'Sawit Sumbermas Sarana Tbk.'},
            {'value': 'SSTM.JK', 'label': 'Sunson Textile Manufacture Tbk.'},
            {'value': 'STAR.JK', 'label': 'Buana Artha Anugerah Tbk.'},
            {'value': 'STTP.JK', 'label': 'Siantar Top Tbk.'},
            {'value': 'SUGI.JK', 'label': 'Sugih Energy Tbk.'},
            {'value': 'SULI.JK', 'label': 'SLJ Global Tbk.'},
            {'value': 'SUPR.JK', 'label': 'Solusi Tunas Pratama Tbk.'},
            {'value': 'SURE.JK', 'label': 'Super Energy Tbk.'},
            {'value': 'SWAT.JK', 'label': 'Sriwahana Adityakarta Tbk.'},
            {'value': 'TALF.JK', 'label': 'Tunas Alfin Tbk.'},
            {'value': 'TAMA.JK', 'label': 'Lancartama Sejati Tbk.'},
            {'value': 'TAMU.JK', 'label': 'Pelayaran Tamarin Samudra Tbk.'},
            {'value': 'TAPG.JK', 'label': 'Triputra Agro Persada Tbk.'},
            {'value': 'TARA.JK', 'label': 'Agung Semesta Sejahtera Tbk.'},
            {'value': 'TAXI.JK', 'label': 'Express Transindo Utama Tbk.'},
            {'value': 'TBIG.JK', 'label': 'Tower Bersama Infrastructure Tbk.'},
            {'value': 'TBLA.JK', 'label': 'Tunas Baru Lampung Tbk.'},
            {'value': 'TBMS.JK', 'label': 'Tembaga Mulia Semanan Tbk.'},
            {'value': 'TCID.JK', 'label': 'Mandom Indonesia Tbk.'},
            {'value': 'TCPI.JK', 'label': 'Transcoal Pacific Tbk.'},
            {'value': 'TDPM.JK', 'label': 'Tridomain Performance Material Tbk.'},
            {'value': 'TEBE.JK', 'label': 'Dana Brata Luhur Tbk.'},
            {'value': 'TECH.JK', 'label': 'Indosterling Technomedia Tbk.'},
            {'value': 'TELE.JK', 'label': 'Tiphone Mobile Indonesia Tbk.'},
            {'value': 'TFAS.JK', 'label': 'Telefast Indonesia Tbk.'},
            {'value': 'TFCO.JK', 'label': 'Tifico Fiber Indonesia Tbk.'},
            {'value': 'TGKA.JK', 'label': 'Tigaraksa Satria Tbk.'},
            {'value': 'TGRA.JK', 'label': 'Terregra Asia Energy Tbk.'},
            {'value': 'TIFA.JK', 'label': 'KDB Tifa Finance Tbk.'},
            {'value': 'TINS.JK', 'label': 'Timah Tbk.'},
            {'value': 'TIRA.JK', 'label': 'Tira Austenite Tbk.'},
            {'value': 'TIRT.JK', 'label': 'Tirta Mahakam Resources Tbk.'},
            {'value': 'TKIM.JK', 'label': 'Pabrik Kertas Tjiwi Kimia Tbk.'},
            {'value': 'TLKM.JK', 'label': 'Telkom Indonesia (Persero) Tbk.'},
            {'value': 'TMAS.JK', 'label': 'Temas Tbk.'},
            {'value': 'TMPO.JK', 'label': 'Tempo Intimedia Tbk.'},
            {'value': 'TNCA.JK', 'label': 'Trimuda Nuansa Citra Tbk.'},
            {'value': 'TOBA.JK', 'label': 'TBS Energi Utama Tbk.'},
            {'value': 'TOPS.JK', 'label': 'Totalindo Eka Persada Tbk.'},
            {'value': 'TOTL.JK', 'label': 'Total Bangun Persada Tbk.'},
            {'value': 'TOTO.JK', 'label': 'Surya Toto Indonesia Tbk.'},
            {'value': 'TOWR.JK', 'label': 'Sarana Menara Nusantara Tbk.'},
            {'value': 'TOYS.JK', 'label': 'Sunindo Adipersada Tbk.'},
            {'value': 'TPIA.JK', 'label': 'Chandra Asri Petrochemical Tbk.'},
            {'value': 'TPMA.JK', 'label': 'Trans Power Marine Tbk.'},
            {'value': 'TRAM.JK', 'label': 'Trada Alam Minera Tbk.'},
            {'value': 'TRIL.JK', 'label': 'Triwira Insanlestari Tbk.'},
            {'value': 'TRIM.JK', 'label': 'Trimegah Sekuritas Indonesia Tbk.'},
            {'value': 'TRIN.JK', 'label': 'Perintis Triniti Properti Tbk.'},
            {'value': 'TRIO.JK', 'label': 'Trikomsel Oke Tbk.'},
            {'value': 'TRIS.JK', 'label': 'Trisula International Tbk.'},
            {'value': 'TRJA.JK', 'label': 'Transkon Jaya Tbk.'},
            {'value': 'TRST.JK', 'label': 'Trias Sentosa Tbk.'},
            {'value': 'TRUE.JK', 'label': 'Triniti Dinamik Tbk.'},
            {'value': 'TRUK.JK', 'label': 'Guna Timur Raya Tbk.'},
            {'value': 'TRUS.JK', 'label': 'Trust Finance Indonesia Tbk.'},
            {'value': 'TSPC.JK', 'label': 'Tempo Scan Pacific Tbk.'},
            {'value': 'TUGU.JK', 'label': 'Asuransi Tugu Pratama Indonesi Tbk.'},
            {'value': 'TURI.JK', 'label': 'Tunas Ridean Tbk.'},
            {'value': 'UANG.JK', 'label': 'Pakuan Tbk.'},
            {'value': 'UCID.JK', 'label': 'Uni-Charm Indonesia Tbk.'},
            {'value': 'UFOE.JK', 'label': 'Damai Sejahtera Abadi Tbk.'},
            {'value': 'ULTJ.JK', 'label': 'Ultra Jaya Milk Industry Tbk.'},
            {'value': 'UNIC.JK', 'label': 'Unggul Indah Cahaya Tbk.'},
            {'value': 'UNIQ.JK', 'label': 'Ulima Nitra Tbk.'},
            {'value': 'UNIT.JK', 'label': 'Nusantara Inti Corpora Tbk.'},
            {'value': 'UNSP.JK', 'label': 'Bakrie Sumatera Plantations Tbk.'},
            {'value': 'UNTR.JK', 'label': 'United Tractors Tbk.'},
            {'value': 'UNVR.JK', 'label': 'Unilever Indonesia Tbk.'},
            {'value': 'URBN.JK', 'label': 'Urban Jakarta Propertindo Tbk.'},
            {'value': 'VICI.JK', 'label': 'Victoria Care Indonesia Tbk.'},
            {'value': 'VICO.JK', 'label': 'Victoria Investama Tbk.'},
            {'value': 'VINS.JK', 'label': 'Victoria Insurance Tbk.'},
            {'value': 'VIVA.JK', 'label': 'Visi Media Asia Tbk.'},
            {'value': 'VOKS.JK', 'label': 'Voksel Electric Tbk.'},
            {'value': 'VRNA.JK', 'label': 'Verena Multi Finance Tbk.'},
            {'value': 'WAPO.JK', 'label': 'Wahana Pronatural Tbk.'},
            {'value': 'WEGE.JK', 'label': 'Wijaya Karya Bangunan Gedung Tbk.'},
            {'value': 'WEHA.JK', 'label': 'WEHA Transportasi Indonesia Tbk.'},
            {'value': 'WICO.JK', 'label': 'Wicaksana Overseas Internation Tbk.'},
            {'value': 'WIFI.JK', 'label': 'Solusi Sinergi Digital Tbk.'},
            {'value': 'WIIM.JK', 'label': 'Wismilak Inti Makmur Tbk.'},
            {'value': 'WIKA.JK', 'label': 'Wijaya Karya (Persero) Tbk.'},
            {'value': 'WINS.JK', 'label': 'Wintermar Offshore Marine Tbk.'},
            {'value': 'WMUU.JK', 'label': 'Widodo Makmur Unggas Tbk.'},
            {'value': 'WOMF.JK', 'label': 'Wahana Ottomitra Multiartha Tbk.'},
            {'value': 'WOOD.JK', 'label': 'Integra Indocabinet Tbk.'},
            {'value': 'WOWS.JK', 'label': 'Ginting Jaya Energi Tbk.'},
            {'value': 'WSBP.JK', 'label': 'Waskita Beton Precast Tbk.'},
            {'value': 'WSKT.JK', 'label': 'Waskita Karya (Persero) Tbk.'},
            {'value': 'WTON.JK', 'label': 'Wijaya Karya Beton Tbk.'},
            {'value': 'YELO.JK', 'label': 'Yelooo Integra Datanet Tbk.'},
            {'value': 'YPAS.JK', 'label': 'Yanaprima Hastapersada Tbk.'},
            {'value': 'YULE.JK', 'label': 'Yulie Sekuritas Indonesia Tbk.'},
            {'value': 'ZBRA.JK', 'label': 'Zebra Nusantara Tbk.'},
            {'value': 'ZINC.JK', 'label': 'Kapuas Prima Coal Tbk.'},
            {'value': 'ZONE.JK', 'label': 'Mega Perintis Tbk.'},
            {'value': 'ZYRX.JK', 'label': 'Zyrexindo Mandiri Buana Tbk.'}

        ],
        placeholder="Pilih Saham Anda",
    ),
    html.Div(id='output-graph')
])

@app.callback(
    Output(component_id='output-graph',component_property='children'),
    [Input(component_id='input',component_property='value')]
)

def update_graph(input_data):
    start = datetime.datetime(2018,1,1)
    end = datetime.datetime.now()
    try:
        (df,_,_,_,_,_,_) = prediction.predict(input_data,start,end)
    except:
        return ""
    return dcc.Graph(id='contoh',
              figure={'data': [{'x': df.index, 'y': df['Adj Close'], 'type': 'line', 'name': 'Harga Saham'},
                               {'x': df.index, 'y': df['F_reg'], 'type': 'line', 'name': 'Linear Regression'},
                               {'x': df.index, 'y': df['F_poly2'], 'type': 'line', 'name': 'Quadratic Regression2'},
                               {'x': df.index, 'y': df['F_poly3'], 'type': 'line', 'name': 'Quadratic Regression3'},
                               {'x': df.index, 'y': df['F_knn'], 'type': 'line', 'name': 'K-Nearest Neighbor'},
                               {'x': df.index, 'y': df['F_svm'], 'type': 'line', 'name': 'Suport Vector Machine'},
                               {'x': df.index, 'y': df['F_tree'], 'type': 'line', 'name': 'Decision Trees'},
                               ],
                'layout': {
                    'title': input_data

                }
            }
    )


if __name__ == '__main__':
    app.run_server(debug=True)
